import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        {children}

        <input type="checkbox" id="my-modal" class="modal-toggle" />
        <div class="modal">
          <div class="modal-box">
            <h3 class="font-bold text-lg">
              Congratulations random Internet user!
            </h3>
            <p class="py-4">
              Youve been selected for a chance to get one year of subscription
              to use Wikipedia for free!
            </p>
            <div class="modal-action">
              <label for="my-modal" class="btn">
                Yay!
              </label>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
